#!/bin/sh

# List up to LIMIT (default 20) files under cwd ordered by recency of modtime.
#
# Usage: find-latest [LIMIT]

# Copyright (C) 2018 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

LIMIT="${1-20}"

find -type f -exec stat -c "%y  %n" {} \; \
  | sort -r -d | head -n ${LIMIT}         \
  | cut --complement -c20-29
