#!/bin/sh

# List up to LIMIT (default 20) files under cwd ordered by recency of modtime.
#
# Usage: find-latest [LIMIT]

# No copyright notice because too short to copyright.  Enjoy.

LIMIT="${1-20}"

find -type f -exec stat -c "%y  %n" {} \; \
  | sort -r -d | head -n ${LIMIT}         \
  | cut --complement -c20-29
