#!/bin/sh

# Show the commit-log difference between two branches.
# Only supports git right now, but could support svn too.

# Copyright (C) 2018 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BRANCH_1="${1}"
BRANCH_2="${2}"

if [ "${BRANCH_1}" = "" ]; then
  echo "ERROR: At least one branch name is required."
  exit 1
fi

if [ "${BRANCH_2}" = "" ]; then
  BRANCH_2="${BRANCH_1}"
  BRANCH_1="master"
fi

TMP_FILE_1=/tmp/log-diff-$$-b1.out
TMP_FILE_2=/tmp/log-diff-$$-b2.out

git log --name-status ${BRANCH_1} > ${TMP_FILE_1}
git log --name-status ${BRANCH_2} > ${TMP_FILE_2}

echo ""
echo "Log difference between '${BRANCH_1}' and '${BRANCH_2}':"
echo ""
diff -u ${TMP_FILE_1} ${TMP_FILE_2}

rm ${TMP_FILE_1} ${TMP_FILE_2}
