#!/bin/sh

### mbox2html: Convert mbox files to browseable HTML trees.
###            Run without arguments to see usage.
###
### (This is essentially a convenience wrapper around the MHonArc
### mail archiver.)
###
### Copyright (C) 2012 Karl Fogel.  This program is free software,
### distributed under a standard BSD 2-Clause open source license;
### see http://opensource.org/licenses/BSD-2-Clause for details.

if [ -z `which mhonarc` ]; then
  echo ""
  echo "  You must have mhonarc installed to run this mbox2html converter."
  echo "  Get mhonarc from http://mhonarc.org/, or if you're on a Debian"
  echo "  GNU/Linux system (or similar, such as Ubuntu), try this:"
  echo ""
  echo "  $ sudo aptitude update && sudo aptitude install mhonarc"
  echo ""
  echo "ERROR: exiting with error because 'mhonarc' not found (see above)"
  exit 1
fi

THIS_CMD="${0}"

if [ "${1}X" = "X" -o "${2}X" = "X" ]; then
  echo ""
  echo "usage: ${THIS_CMD} MBOX_FILE HTML_DEST_DIR"
  echo ""
  echo "  MBOX_FILE is a file in mbox format containing one or more messages"
  echo ""
  echo "  HTML_DEST_DIR is the new directory in which ${THIS_CMD} will"
  echo "  create the html tree of messages, along with a threads.html and"
  echo "  index.html file (usually you want to visit threads.html first)."
  echo ""
  exit 1
fi
  
MBOX_FILE="${1}"
HTML_DEST_DIR="${2}"

if [ -d ${HTML_DEST_DIR} ]; then
  echo "Please move directory '${HTML_DEST_DIR}' aside."
  echo "(${THIS_CMD} wants to create a new directory there)"
  exit 1
elif [ -e ${HTML_DEST_DIR} ]; then
  echo "Please move file '${HTML_DEST_DIR}' aside."
  echo "(${THIS_CMD} wants to create a new directory of that name)"
  exit 1
fi

mkdir ${HTML_DEST_DIR}

mhonarc ${MBOX_FILE} -add -folrefs -main -reverse -multipg  \
                     -idxfname index.html                   \
                     -tidxfname threads.html                \
                     -attachmentdir attachments             \
                     -outdir ${HTML_DEST_DIR}

echo ""
echo "Done -- now visit ${HTML_DEST_DIR}/threads.html in a browser."
echo ""
