#!/usr/bin/env python3

# Copyright (C) 2018 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

"""Read lines from stdin & print them stdout, chopping them if too long.

By default, "too long" is > 256 characters, but if you pass an
argument it will be used as the chop limit instead.

Use this when you're generating output that might have some very long
lines (e.g., thousands of characters long, say from minified
Javascript files) and you don't want those huge lines to take over
your terminal window, or your Emacs shell buffer, or wherever you're
sending your output.  Example usages:

  $ grep -r "foo" . | no-longer-than
  $ git diff | no-longer-than

"""

import sys

limit = 256

if len(sys.argv) > 1:
    limit = int(sys.argv[1])

line = sys.stdin.readline()
while line != "":
    sys.stdout.write(line[0:limit])
    if len(line) > limit and line[-1] == "\n":
        sys.stdout.write('\n')
    line = sys.stdin.readline()
