#!/usr/bin/env python3

# Print out a list of all OTS servers and their SSH fingerprints.

# This program is in the public domain.  It was written in 2020 by
# Open Tech Strategies, LLC, and is too small for us to bother to
# copyright it for formal open source licensing.  Use it as you will.

import os
import yaml   # Might need to do 'pip install pyyaml' first
import subprocess

servers_yaml = os.path.join(os.getenv("OTSDIR"), 
                            "infra", 
                            "server-inventory.yaml")

# This will become a dictionary parsed from 'server-inventory.yaml'.
servers = None

with open(servers_yaml, 'r') as input:
    try:
        servers = yaml.safe_load(input)
    except yaml.YAMLError as e:
        print("ERROR: %s" % e)

for server in servers:
    print("Hostname(s):", end="")
    if len(server["hostnames"]) == 0:
        print(" N/A")
    else:
        for h in server["hostnames"]:
            print(" %s" % h, end="")
        print("")
    print("IP(s):      ", end="")
    if len(server["ip_addrs"]) == 0:
        print(" N/A")
    else:
        for a in server["ip_addrs"]:
            print(" %s" % a, end="")
        print("")
    print("SSH Key Fingerprint(s):")
    for key_type in server["ssh_host_key"]:
        actual_key = server["ssh_host_key"][key_type]
        res = subprocess.run(['ssh-keygen', '-lf-'], 
                             input = actual_key.encode('utf-8'),
                             stdout=subprocess.PIPE, 
                             stderr=subprocess.STDOUT)
        fingerprint = res.stdout.decode("utf-8").strip()
        print("  %s: %s" % (key_type.rjust(10), fingerprint))
    print("")
