#!/usr/bin/env python3

# Print out a list of all OTS servers and their SSH fingerprints.

# Copyright (C) 2020 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import os
import yaml   # Might need to do 'pip install pyyaml' first
import subprocess

servers_yaml = os.path.join(os.getenv("OTSDIR"), 
                            "infra", 
                            "server-inventory.yaml")

# This will become a dictionary parsed from 'server-inventory.yaml'.
servers = None

with open(servers_yaml, 'r') as input:
    servers = yaml.safe_load(input)

for server in servers:
    print("Hostname(s):", end="")
    if len(server["hostnames"]) == 0:
        print(" N/A")
    else:
        for h in server["hostnames"]:
            print(" %s" % h, end="")
        print("")
    print("IP(s):      ", end="")
    if len(server["ip_addrs"]) == 0:
        print(" N/A")
    else:
        for a in server["ip_addrs"]:
            print(" %s" % a, end="")
        print("")
    print("SSH Key Fingerprint(s):")
    for key_type in server["ssh_host_key"]:
        actual_key = server["ssh_host_key"][key_type]
        res = subprocess.run(['ssh-keygen', '-lf-'], 
                             input = actual_key.encode('utf-8'),
                             stdout=subprocess.PIPE, 
                             stderr=subprocess.STDOUT)
        fingerprint = res.stdout.decode("utf-8").strip()
        print("  %s: %s" % (key_type.rjust(10), fingerprint))
    print("")
