#!/bin/sh

# Grep recursively, with protection against long lines (e.g., JS .min files).
# If -i flag is given first, then grep case-insensitively.
# If second argument is given, it is root from which to start recursion.

# Too tiny to copyright under an open source license.  Use as you please.

# This depends on the 'no-longer-than' utility being in PATH.
# It is available from the same repository.

GREP_CMD='grep -rE'

if [ "${1}X" = "-iX" ]; then
    GREP_CMD='grep -i -rE'
    shift
fi

if [ "${1}X" = "X" ]; then
    PGM_NAME=`basename ${0}`
    echo "${PGM_NAME}: " \
         "Grep recursively, protecting against long lines.  Usage:" >&2
    echo "" >&2
    echo "  ${PGM_NAME} [-i] STRING [FILE_OR_DIRECTORY_ROOT]" >&2
    echo "" >&2
    echo "  (FILE_OR_DIRECTORY_ROOT defaults to '.')" >&2
    echo "" >&2
    exit 1
fi

ROOT="."
if [ "${2}X" != "X" ]; then
    ROOT="${2}"
fi

${GREP_CMD} "${1}" "${ROOT}" | no-longer-than | grep -v -E '^Binary file .* matches$'
