#!/bin/sh

# Test the ../git-over-here script.  Invoke this from ../, that is,
# from the directory that contains 'git-over-here'.

TEST_DIR="test-tmp-$$"
mkdir "${TEST_DIR}"
mkdir "${TEST_DIR}"/bar
mkdir "${TEST_DIR}"/bar/qux

for name in ots-tools ots-doctools ots-bookkeeping; do
  git clone git@github.com:OpenTechStrategies/${name}.git "${TEST_DIR}"/${name}
  cp -a "${TEST_DIR}"/"${name}" "${TEST_DIR}"/bar/
  cp -a "${TEST_DIR}"/"${name}" "${TEST_DIR}"/bar/qux/
  # Make some tweaks to check the exception-case handling.
  if [ "${name}" = "ots-tools" ]; then
    (cd "${TEST_DIR}"/bar/"${name}"; git checkout 19-specify-git-svn-username)
    echo "FISH" >> "${TEST_DIR}"/bar/qux/"${name}"/README
  fi
  ./git-over-here -r git@github.com:OpenTechStrategies/"${name}".git \
                     git@code.librehq.com:ots/"${name}".git          \
                  -b master main "${TEST_DIR}"
done

# Clean up.  Of course, if you need to inspect the test directory
# after a test run, you might want to temporarily comment this out.
rm -rf "${TEST_DIR}"
